# Generated by Django 2.2.6 on 2019-10-16 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.PositiveIntegerField(default=1234567, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)]),
        ),
    ]
